#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevPlusAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Runtime.Serialization;

    public partial class VU_DataSourceDataContext : DataContext
	{
		
		private static MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
        partial void InserttblLocation(tblLocation instance);
        partial void UpdatetblLocation(tblLocation instance);
        partial void DeletetblLocation(tblLocation instance);
        partial void InserttblProduct(tblProduct instance);
        partial void UpdatetblProduct(tblProduct instance);
        partial void DeletetblProduct(tblProduct instance);
        #endregion

        public VU_DataSourceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VU_DataSourceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VU_DataSourceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VU_DataSourceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public Table<vwCreateEquipOrder> vwCreateEquipOrders
        {
            get
            {
                return this.GetTable<vwCreateEquipOrder>();
            }
        }

        public System.Data.Linq.Table<vwFoundOrder> vwFoundOrders
        {
            get
            {
                return this.GetTable<vwFoundOrder>();
            }
        }

        public System.Data.Linq.Table<vwCustomer> vwCustomers
        {
            get
            {
                return this.GetTable<vwCustomer>();
            }
        }

        public Table<vwVendor> vwVendors
        {
            get
            {
                return this.GetTable<vwVendor>();
            }
        }

        public System.Data.Linq.Table<tblLocation> tblLocations
        {
            get
            {
                return this.GetTable<tblLocation>();
            }
        }

        public System.Data.Linq.Table<tblProduct> tblProducts
        {
            get
            {
                return this.GetTable<tblProduct>();
            }
        }

        public System.Data.Linq.Table<viewCategories> viewCategories
        {
            get
            {
                return this.GetTable<viewCategories>();
            }
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.RevSP_Util_LT_CreateEquip_Order")]
        public ISingleResult<vwCreateEquipOrder> RevSP_Util_LT_CreateEquip_Order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iNumberOfProductsToCreate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iNumberOfAssetsPerProduct, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(2)")] string vcPrefix, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> bCreateCategory, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> bIsBarcodeTracked, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iProductConfigurationID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iNumberOfCompPerProduct, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iNumberOfAccessoryPerProduct, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iNumberOfAltPerProduct, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iFromLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iToLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> bCreateOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iOrderFormatType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> iOrderID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iNumberOfProductsToCreate, iNumberOfAssetsPerProduct, vcPrefix, bCreateCategory, bIsBarcodeTracked, iProductConfigurationID, iNumberOfCompPerProduct, iNumberOfAccessoryPerProduct, iNumberOfAltPerProduct, iFromLocation, iToLocation, bCreateOrder, iOrderFormatType, iOrderID);
            return ((ISingleResult<vwCreateEquipOrder>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.RevSP_Util_LT_GetOrder")]
        public ISingleResult<vwFoundOrder> RevSP_Util_LT_GetOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "PullStatus", DbType = "Int")] System.Nullable<int> pullStatus)
        {
            IExecuteResult result = ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pullStatus);
            return ((ISingleResult<vwFoundOrder>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.RevSP_Util_LT_GetCustCode")]
        public ISingleResult<vwCustomer> RevSP_Util_LT_GetCustCode()
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
            return ((ISingleResult<vwCustomer>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.RevSP_Util_LT_GetCategories")]
        public ISingleResult<viewCategories> RevSP_Util_LT_GetCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ParentID", DbType = "Int")] System.Nullable<int> parentID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentID);
            return ((ISingleResult<viewCategories>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.RevSP_Util_LT_GetVendor")]
        public ISingleResult<vwVendor> RevSP_Util_LT_GetVendor([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IsPurchase", DbType = "Bit")] System.Nullable<bool> isPurchase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IsShip", DbType = "Bit")] System.Nullable<bool> isShip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IsRepair", DbType = "Bit")] System.Nullable<bool> isRepair, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IsOther", DbType = "Bit")] System.Nullable<bool> isOther, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IsSubRent", DbType = "Bit")] System.Nullable<bool> isSubRent)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPurchase, isShip, isRepair, isOther, isSubRent);
            return ((ISingleResult<vwVendor>)(result.ReturnValue));
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class vwCreateEquipOrder
    {

        private int _OrderID;

        private int _ProductID;

        private string _ProductCode;

        private int _AssetID;

        private string _Barcode;

        private int _ToLocationID;

        private string _ToLocationName;

        private int _CustomerID;

        public vwCreateEquipOrder()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OrderID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                if ((this._OrderID != value))
                {
                    this._OrderID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProductID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                if ((this._ProductID != value))
                {
                    this._ProductID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProductCode", DbType = "varchar(20)", CanBeNull = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string ProductCode
        {
            get
            {
                return this._ProductCode;
            }
            set
            {
                if ((this._ProductCode != value))
                {
                    this._ProductCode = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AssetID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public int AssetID
        {
            get
            {
                return this._AssetID;
            }
            set
            {
                if ((this._AssetID != value))
                {
                    this._AssetID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Barcode", DbType = "varchar(30)", CanBeNull = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                if ((this._Barcode != value))
                {
                    this._Barcode = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ToLocationID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public int ToLocationID
        {
            get
            {
                return this._ToLocationID;
            }
            set
            {
                if ((this._ToLocationID != value))
                {
                    this._ToLocationID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ToLocationName", DbType = "varchar(100)", CanBeNull = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string ToLocationName
        {
            get
            {
                return this._ToLocationName;
            }
            set
            {
                if ((this._ToLocationName != value))
                {
                    this._ToLocationName = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CustomerID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                if ((this._CustomerID != value))
                {
                    this._CustomerID = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class vwFoundOrder
    {

        private int _OrderID;

        private int _OrderStatusID;

        private int _CustomerID;

        public vwFoundOrder()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OrderID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                if ((this._OrderID != value))
                {
                    this._OrderID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OrderStatusID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int OrderStatusID
        {
            get
            {
                return this._OrderStatusID;
            }
            set
            {
                if ((this._OrderStatusID != value))
                {
                    this._OrderStatusID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CustomerID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                if ((this._CustomerID != value))
                {
                    this._CustomerID = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class vwCustomer
    {

        private string _CustomerCode;

        public vwCustomer()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CustomerCode", DbType = "varchar(20)", CanBeNull = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string CustomerCode
        {
            get
            {
                return this._CustomerCode;
            }
            set
            {
                if ((this._CustomerCode != value))
                {
                    this._CustomerCode = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class vwVendor
    {

        private string _VenderCode;

        private System.Nullable<bool> _IsShip;

        private System.Nullable<bool> _Active;

        private System.Nullable<bool> _Deleted;

        private System.Nullable<int> _EntityID;

        private string _Name;

        private System.Nullable<bool> _IsPurchase;

        public vwVendor()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "VendorCode", Storage = "_VenderCode", DbType = "varchar(250)")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string VenderCode
        {
            get
            {
                return this._VenderCode;
            }
            set
            {
                if ((this._VenderCode != value))
                {
                    this._VenderCode = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsShip", DbType = "bit")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Nullable<bool> IsShip
        {
            get
            {
                return this._IsShip;
            }
            set
            {
                if ((this._IsShip != value))
                {
                    this._IsShip = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Active", DbType = "bit")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                if ((this._Active != value))
                {
                    this._Active = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Deleted", DbType = "bit")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.Nullable<bool> Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                if ((this._Deleted != value))
                {
                    this._Deleted = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EntityID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.Nullable<int> EntityID
        {
            get
            {
                return this._EntityID;
            }
            set
            {
                if ((this._EntityID != value))
                {
                    this._EntityID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Name", DbType = "varchar(250)")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsPurchase", DbType = "bit")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.Nullable<bool> IsPurchase
        {
            get
            {
                return this._IsPurchase;
            }
            set
            {
                if ((this._IsPurchase != value))
                {
                    this._IsPurchase = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.tblLocation")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class tblLocation : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _LocationID;

        private string _LocationName;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnLocationIDChanging(int value);
        partial void OnLocationIDChanged();
        partial void OnLocationNameChanging(string value);
        partial void OnLocationNameChanged();
        #endregion

        public tblLocation()
        {
            this.Initialize();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocationID", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                if ((this._LocationID != value))
                {
                    this.OnLocationIDChanging(value);
                    this.SendPropertyChanging();
                    this._LocationID = value;
                    this.SendPropertyChanged("LocationID");
                    this.OnLocationIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocationName", DbType = "VarChar(100) NOT NULL", CanBeNull = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string LocationName
        {
            get
            {
                return this._LocationName;
            }
            set
            {
                if ((this._LocationName != value))
                {
                    this.OnLocationNameChanging(value);
                    this.SendPropertyChanging();
                    this._LocationName = value;
                    this.SendPropertyChanged("LocationName");
                    this.OnLocationNameChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void Initialize()
        {
            OnCreated();
        }

        [global::System.Runtime.Serialization.OnDeserializingAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public void OnDeserializing(StreamingContext context)
        {
            this.Initialize();
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.tblProducts")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    public partial class tblProduct : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ProductID;

        private string _ProductCode;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        partial void OnProductCodeChanging(string value);
        partial void OnProductCodeChanged();
        #endregion

        public tblProduct()
        {
            this.Initialize();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProductID", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                if ((this._ProductID != value))
                {
                    this.OnProductIDChanging(value);
                    this.SendPropertyChanging();
                    this._ProductID = value;
                    this.SendPropertyChanged("ProductID");
                    this.OnProductIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProductCode", DbType = "VarChar(20)")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string ProductCode
        {
            get
            {
                return this._ProductCode;
            }
            set
            {
                if ((this._ProductCode != value))
                {
                    this.OnProductCodeChanging(value);
                    this.SendPropertyChanging();
                    this._ProductCode = value;
                    this.SendPropertyChanged("ProductCode");
                    this.OnProductCodeChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void Initialize()
        {
            OnCreated();
        }

        [global::System.Runtime.Serialization.OnDeserializingAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public void OnDeserializing(StreamingContext context)
        {
            this.Initialize();
        }
    }

    [Table(Name = "")]
    [DataContract()]
    public partial class viewCategories
    {

        private int? _CategoryParentID;

        private int? _CategoryID;

        private int? _ParentID;

        private string _Name;

        private string _ParentName;

        private bool? _Active;

        public viewCategories()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CategoryParentID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Nullable<int> CategoryParentID
        {
            get
            {
                return this._CategoryParentID;
            }
            set
            {
                if ((this._CategoryParentID != value))
                {
                    this._CategoryParentID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CategoryID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Nullable<int> CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                if ((this._CategoryID != value))
                {
                    this._CategoryID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ParentID", DbType = "int")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public System.Nullable<int> ParentID
        {
            get
            {
                return this._ParentID;
            }
            set
            {
                if ((this._ParentID != value))
                {
                    this._ParentID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Name", DbType = "VarChar(50)")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ParentName", DbType = "VarChar(50)")]
        [global::System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string ParentName
        {
            get
            {
                return this._ParentName;
            }
            set
            {
                if ((this._ParentName != value))
                {
                    this._ParentName = value;
                }
            }
        }

        [Column(Storage = "_Active", DbType = "bit")]
        [DataMember(Order = 6)]
        public System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                if ((this._Active != value))
                {
                    this._Active = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
